[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Ship the Stripe SDK with the lambda
  external_node_modules = ["stripe"]
  # Make sure shared code/templates are bundled with functions
  included_files = [
    "netlify/functions/_lib/**",
    "netlify/functions/_emails/**",
    "Thomas.jpg",
    "Avery.jpg"
  ]

# Pretty /api/* -> Functions (e.g., /api/get-gallery, /api/stripe-webhook)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Optional: direct preview links like /preview/<key>
[[redirects]]
  from = "/preview/*"
  to   = "/.netlify/functions/preview/:splat"
  status = 200
  force  = true
