[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  # Include the shared server lib and the local images you want to seed
  included_files = [
    "netlify/functions/_lib/**",
    "Thomas.jpg",
    "Avery.jpg"
  ]

# Pretty /api/* to Functions (so /api/get-gallery, /api/preview, etc.)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Optional: path-style preview URL support in addition to /api/preview?key=...
# Keep this only if you want to hit /preview/<key> directly.
[[redirects]]
  from = "/preview/*"
  to   = "/.netlify/functions/preview/:splat"
  status = 200
  force  = true
